# auto-generated by optuna_tuner.py
LGB_BEST = {
  "num_leaves": 39,
  "max_depth": 5,
  "learning_rate": 0.013008657537229686,
  "feature_fraction": 0.6301029627298821,
  "bagging_fraction": 0.7258272566476676,
  "bagging_freq": 8,
  "min_child_samples": 161,
  "reg_alpha": 7.543782589628926,
  "reg_lambda": 7.466264552609727,
  "min_split_gain": 0.48768820099532245
}
XGB_BEST = {
  "max_depth": 4,
  "learning_rate": 0.06182045070472739,
  "subsample": 0.777581044269963,
  "colsample_bytree": 0.7388742834599537,
  "min_child_weight": 5,
  "gamma": 0.2800187824214299,
  "reg_alpha": 8.592776110908002,
  "reg_lambda": 4.685337471290121
}
